"""Pydantic schemas for authentication endpoints."""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, EmailStr, Field, model_validator

from app.db.models import UserRole


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    full_name: str = Field(min_length=1, max_length=255)
    # Exactly one of these two must be set: create a brand-new organization
    # (caller becomes its Company Admin), or join an existing one by
    # consuming an invitation generated by that org's admin.
    organization_name: str | None = Field(default=None, min_length=1, max_length=255)
    invite_token: str | None = Field(default=None, min_length=1)

    @model_validator(mode="after")
    def _exactly_one_join_path(self) -> "RegisterRequest":
        if bool(self.organization_name) == bool(self.invite_token):
            raise ValueError("Provide exactly one of organization_name or invite_token.")
        return self


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class RefreshRequest(BaseModel):
    refresh_token: str


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"


class UserResponse(BaseModel):
    id: uuid.UUID
    org_id: uuid.UUID
    org_name: str
    email: EmailStr
    full_name: str
    role: UserRole
    expires_at: datetime | None = None

    model_config = {"from_attributes": True}
